### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zifeixu85** [onvno/resizeup#1]
![image](https://user-images.githubusercontent.com/6513625/30961671-91cca8aa-a40c-11e7-8752-06157dbd2b40.png)

**Comment by onvno** [comment]
报错应该是缺了`request`这个包，刚更新了插件可以试试看。
如果还是报错，直接本地安装下依赖包：
```
$ pip install requests
```

**Comment by zifeixu85** [comment]
![image](https://user-images.githubusercontent.com/6513625/31019282-c6212b88-a4f4-11e7-8c91-f857b4b26c46.png)

重新下载安装还是不行，后根据提示折腾完毕：

1. 安装 pip，然后安装 requests（我不是程序员，这一步折腾很久，资料网上查的）
2. 发现 tinypng API 是必填项，填好后可以正常使用

一个反馈，就是文件后缀加上了 MD5 值，感觉略麻烦，也谢谢作者提供的插件。

**Comment by onvno** [comment]
@zifeixu85 加md5看着确实不太好看，不过这样能避免两种情况：
1.文件名相同的图片直接上传，如果有同名文件，会被覆盖掉。加md5能避免文件重名。
2.同一文件，如果只是文件名不同，会导致重复上传，浪费流量。加md5能避免重复上传。

不过根建议，md5确实可以少取几位
